apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp
  labels:
    type: frontend
spec:
  template:
    metadata:
      name: my-nginx
      labels:
        app: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx
