apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
spec:
  selector:
    matchLabels:
      app: myapp-frontend
  template:
    metadata:
      name: myapp-frontend
      labels:
        app: myapp-frontend
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 5
